#!/bin/bash
echo ""
echo "============================================"
echo "  LWS Operator Installed Successfully!"
echo "============================================"
echo ""
echo "Verify installation:"
echo "  kubectl get pods -n openshift-lws-operator"
echo "  kubectl get leaderworkersetoperator cluster"
echo ""
echo "Create a LeaderWorkerSet:"
echo "  kubectl apply -f - <<EOF"
echo "  apiVersion: leaderworkerset.x-k8s.io/v1"
echo "  kind: LeaderWorkerSet"
echo "  metadata:"
echo "    name: my-lws"
echo "  spec:"
echo "    replicas: 2"
echo "    leaderWorkerTemplate:"
echo "      size: 3"
echo "      leaderTemplate:"
echo "        metadata:"
echo "          labels:"
echo "            role: leader"
echo "        spec:"
echo "          containers:"
echo "          - name: main"
echo "            image: nginx"
echo "      workerTemplate:"
echo "        spec:"
echo "          containers:"
echo "          - name: main"
echo "            image: nginx"
echo "  EOF"
echo ""
